### PR TITLE
[skip ci] swap codeowners

### PR DESCRIPTION
**Pull request by robmorgan**
* Swap Petri for Rob

Would somebody mind merging this for me?

### CODE REVIEW

**Comment by brikis98** [comment]
Rob, as mentioned in the other PR, this one should be you and Etiene. Could you update accordingly? Also, as the owner, I've given you write access to this repo, so you should now be able to merge.

**Comment by robmorgan** [comment]
@brikis98 can you approve the PR?

**Comment by robmorgan** [comment]
@brikis98 and give me write access? 👍

**Comment by brikis98** [comment]
You have it?

Screen Shot 2020-02-06 at 4 35 34 PM

Might have to go to https://github.com/hashicorp/terraform-aws-vault/invitations to accept the invite? Same for the other HashiCorp repos.

**Comment by robmorgan** [comment]
@brikis98 Thx, that was the issue.

**Pull request merged**
