### PR TITLE
Bump tf to version 1.0

### PR DESCRIPTION
**Pull request by bwhaley**
Updates tests to use Terraform 1.0.

### CODE REVIEW

**Review by zackproser — APPROVED** [review]
LGTM

**Comment by rileytg** [comment]
this will break variables in at least here https://github.com/hashicorp/terraform-aws-vault/tree/master/modules/vault-cluster
```
╷
│ Error: Invalid quoted type constraints
│ 
│   on .terraform/modules/vault_cluster/modules/vault-cluster/variables.tf line 24, in variable "allowed_inbound_cidr_blocks":
│   24:   type        = "list"
│ 
│ Terraform 0.11 and earlier required type constraints to be given in quotes, but that form is now deprecated and will be removed in a future version of
│ Terraform. Remove the quotes around "list" and write list(string) instead to explicitly indicate that the list elements are strings.
```

opening a pull for that now

**Comment by rileytg** [comment]
scratch that... im working off old code. everything i use is working with tf 1!

**Review by brikis98 — APPROVED** [review]
LGTM! I'll kick off tests now.

**Comment by brikis98** [comment]
@bwhaley Looks like there were some test failures

**Comment by bwhaley** [comment]
Mind kicking off the tests again?

**Comment by brikis98** [comment]
Tests are running again!

**Comment by bwhaley** [comment]
Tests appear to be passing.

**Comment by brikis98** [comment]
Indeed they are! Merging now.

**Comment by brikis98** [comment]
https://github.com/hashicorp/terraform-aws-vault/releases/tag/v0.17.0

**Pull request merged**
