### PR TITLE
Fixed aws-cli package name

### PR DESCRIPTION
**Pull request by aanafcheh**
Issue #79 

- Corrected package name for yum based distributions

### CODE REVIEW

**Comment by aanafcheh** [comment]
I'm not quite sure how to do the automated tests, but I did find out about one of your other tools Terratest. I'll try to make it work. Would appreciate any advice or guides.

**Comment by brikis98** [comment]
The tests are already in place. You just need to run them per these docs: https://github.com/hashicorp/terraform-aws-vault/tree/master/test

**Comment by aanafcheh** [comment]
The test passed. Here's some of the output: https://gist.github.com/aanafcheh/1acce98ad693d02c3ba54fd5ffe1bf47

**Comment by brikis98** [comment]
Wonderful, thank you!

**Comment by brikis98** [comment]
https://github.com/hashicorp/terraform-aws-vault/releases/tag/v0.9.1

**Pull request merged**
