### PR TITLE
Add iam instance profile outputs

### PR DESCRIPTION
**Pull request by nicgrayson**

### CODE REVIEW

**Comment by brikis98** [comment]
Thanks for the PR! We need to resolve https://github.com/hashicorp/terraform-aws-vault/issues/196 first and can then take a look at this PR. Hoping to get to that in the next week or two. If anyone has cycles to look into it before then, help is very appreciated!

**Review by brikis98 — COMMENTED** [review]
OK, thank you for your patience! We merged fixes in #195. Could you rebase?

**Comment by nicgrayson** [comment]
@brikis98 rebased

**Comment by brikis98** [comment]
Great, thanks! Kicking off tests now.

**Comment by brikis98** [comment]
Doh! Tests failed due to the AWS account we use for tested exceeding some resource limits... Cleaning up now, please hold...

**Comment by brikis98** [comment]
Re-running tests now...

**Comment by brikis98** [comment]
Tests passed! Merging now.

**Comment by brikis98** [comment]
https://github.com/hashicorp/terraform-aws-vault/releases/tag/v0.13.10

**Pull request merged**
