### PR TITLE
Ignore changes to load balancers in vault-cluster ASG

### LINKED ISSUE #210: AWS Provider >=3.0.0 ASG inline load_balancers removing attached load balancers
Since the AWS Provider's update to v3.0.0, the relationship between an `aws_autoscaling_group` and `aws_autoscaling_attachment` has become more strictly conflicted. Since the `vault-cluster` module does not define a load balancer, and a load balancer must be attached by an autoscaling attachment from outside the `vault-cluster` module, the autoscaling groups should ignore changes to the `load_balancers` and `target_group_arns`.

In my case, despite the `vault-elb` module defining the autoscaling attachment, the AWS provider is trying to remove the relationship in favor of the empty inline `load_balancers` argument. There is a similar issue in the `terraform-aws-consul` module.

This conflict is documented in the AWS Provider's documentation [here](https://registry.terraform.io/providers/hashicorp/aws/3.0.0/docs/resources/autoscaling_attachment), and there is [an open issue](https://github.com/terraform-providers/terraform-provider-aws/issues/14540) on the AWS Provider repo.

### PR DESCRIPTION
**Pull request by andrew-womeldorf**
Fixes #210

### CODE REVIEW

**Comment by brikis98** [comment]
Thanks for the PR! We had a few issues to fix with this repo that were done in https://github.com/hashicorp/terraform-aws-vault/pull/195. Now that is merged in, could you rebase, and then I can kick off tests?

**Comment by andrew-womeldorf** [comment]
@brikis98 rebased!

**Comment by brikis98** [comment]
Thanks! Kicking off tests now.

**Comment by brikis98** [comment]
Tests failed originally, but it turned out to be due to an issue in the default VPC in the AWS account we use for testing. I fixed that issue, re-ran the tests, and they passed. Merging now!

**Comment by brikis98** [comment]
https://github.com/hashicorp/terraform-aws-vault/releases/tag/v0.13.11

**Pull request merged**
